# Build stage ------------
FROM node:20.11.0 AS build

# 환경변수 받기
ARG VITE_API_BASE_URL
ARG VITE_KAKAO_API_KEY
ARG VITE_KAKAO_RESTAPI_KEY
ARG VITE_FIREBASE_VAPID_KEY
ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_SENDER_ID
ARG VITE_FIREBASE_APP_ID
ARG VITE_FIREBASE_MEASUREMENT_ID

# 환경변수 설정
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_KAKAO_API_KEY=$VITE_KAKAO_API_KEY
ENV VITE_KAKAO_RESTAPI_KEY=$VITE_KAKAO_RESTAPI_KEY
ENV VITE_FIREBASE_VAPID_KEY=$VITE_FIREBASE_VAPID_KEY
ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY
ENV VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN
ENV VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID
ENV VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET
ENV VITE_FIREBASE_SENDER_ID=$VITE_FIREBASE_SENDER_ID
ENV VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID
ENV VITE_FIREBASE_MEASUREMENT_ID=$VITE_FIREBASE_MEASUREMENT_ID

WORKDIR /usr/src/app
COPY . .
RUN npm ci
RUN npm run build

# Serve stage ------------
FROM node:20.11.0-alpine
WORKDIR /app
COPY --from=build /usr/src/app/dist ./dist
RUN npm install -g serve
EXPOSE 5173
USER node
CMD ["serve", "-s", "dist", "-l", "5173"]
